pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
        AWS_DEFAULT_REGION    = 'eu-north-1'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Security Scan') {
            steps {
                sh '''
                  trivy config --severity HIGH,CRITICAL --exit-code 1 terraform/
                '''
            }
        }

        stage('Terraform Init & Plan') {
            steps {
                sh '''
                  cd terraform
                  terraform init
                  terraform plan
                '''
            }
        }
    }
}
